// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"
	"net"

	"example.com/testcli/container"
	"example.com/testcli/image"
	"example.com/testcli/network"
	"example.com/testcli/volume"
	"github.com/lachaloupe/cli"
)

func DockerArgsFrom(ctx context.Context) DockerArgs {
	return ctx.Value(cli.Args("/")).(DockerArgs)
}

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path: "/",
		Help: "A self-sufficient runtime for containers",
		Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
			s := DockerArgs{}

			if p := cmd.Get("api-version"); p != nil && p.Value != nil {
				s.ApiVersion = p.Value.(string)
			}

			if p := cmd.Get("config"); p != nil && p.Value != nil {
				s.Config = p.Value.(string)
			}

			if p := cmd.Get("debug"); p != nil && p.Value != nil {
				s.Debug = p.Value.(bool)
			}

			if p := cmd.Get("host"); p != nil && p.Value != nil {
				s.Host = p.Value.([]string)
			}

			if p := cmd.Get("tls"); p != nil && p.Value != nil {
				s.Tls = p.Value.(bool)
			}

			if p := cmd.Get("tlscacert"); p != nil && p.Value != nil {
				s.Tlscacert = p.Value.(string)
			}

			err := errors.Join((RunDocker)(ctx, s), cmd.Cleanup())
			if err != nil {
				return ctx, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			ctx = context.WithValue(ctx, cli.Args("/"), s)
			return ctx, nil
		},
		Args: []*cli.Arg{
			{
				Name: "api-version",
				Type: "string",
				Help: "Set the API version to use.",
			},
			{
				Name: "config",
				Type: "string",
				Help: "Location of client configuration files.",
				Labels: map[string][]string{
					"path": {
						"clean",
					},
				},
				Validate: cli.PathValidate,
			},
			{
				Name:    "debug",
				Type:    "bool",
				Aliases: []string{"D"},
				Help:    "Enable debug mode.",
			},
			{
				Name:    "host",
				Type:    "[]string",
				Aliases: []string{"H"},
				Help:    "Daemon socket to connect to.",
				Defaults: []string{
					"unix:///var/run/docker.sock",
				},
			},
			{
				Name: "tls",
				Type: "bool",
				Help: "Use TLS.",
			},
			{
				Name: "tlscacert",
				Type: "string",
				Help: "Trust certs signed only by this CA.",
				Labels: map[string][]string{
					"path": {
						"file",
						"clean",
					},
				},
				Validate: cli.PathValidate,
			},
		},
		Commands: []*cli.Command{
			{
				Name: "image",
				Path: "/image",
				Help: "Manage images",
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {

					ctx = context.WithValue(ctx, cli.Parent{}, "/image")
					return ctx, nil
				},
				Commands: []*cli.Command{
					{
						Name: "ls",
						Path: "/image/ls",
						Help: "RunImageLs lists images.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := image.LsArgs{}

							if p := cmd.Get("all"); p != nil && p.Value != nil {
								s.All = p.Value.(bool)
							}

							if p := cmd.Get("digests"); p != nil && p.Value != nil {
								s.Digests = p.Value.(bool)
							}

							if p := cmd.Get("format"); p != nil && p.Value != nil {
								s.Format = p.Value.(string)
							}

							if p := cmd.Get("no-trunc"); p != nil && p.Value != nil {
								s.NoTrunc = p.Value.(bool)
							}

							if p := cmd.Get("quiet"); p != nil && p.Value != nil {
								s.Quiet = p.Value.(bool)
							}

							if p := cmd.Get("filter"); p != nil && p.Value != nil {
								s.Filter = p.Value.([]string)
							}

							err := errors.Join((image.RunLs)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/image/ls")
							ctx = context.WithValue(ctx, cli.Args("/image/ls"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "all",
								Type:    "bool",
								Aliases: []string{"a"},
								Help:    "Show all images.",
							},
							{
								Name: "digests",
								Type: "bool",
								Help: "Show digests.",
							},
							{
								Name: "format",
								Type: "string",
								Help: "Pretty-print images using a Go template.",
							},
							{
								Name: "no-trunc",
								Type: "bool",
								Help: "Don't truncate output.",
							},
							{
								Name:    "quiet",
								Type:    "bool",
								Aliases: []string{"q"},
								Help:    "Only show image IDs.",
							},
							{
								Name:    "filter",
								Type:    "[]string",
								Aliases: []string{"f"},
								Help:    "Provide filter values.",
							},
						},
					},
					{
						Name: "pull",
						Path: "/image/pull",
						Help: "RunImagePull pulls an image.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := image.PullArgs{}

							if p := cmd.Get("all-tags"); p != nil && p.Value != nil {
								s.AllTags = p.Value.(bool)
							}

							if p := cmd.Get("platform"); p != nil && p.Value != nil {
								s.Platform = p.Value.(string)
							}

							if p := cmd.Get("quiet"); p != nil && p.Value != nil {
								s.Quiet = p.Value.(bool)
							}

							if p := cmd.Get("image"); p != nil && p.Value != nil {
								s.Image = p.Value.(string)
							}

							err := errors.Join((image.RunPull)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/image/pull")
							ctx = context.WithValue(ctx, cli.Args("/image/pull"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "all-tags",
								Type:    "bool",
								Aliases: []string{"a"},
								Help:    "Download all tagged images in the repository.",
							},
							{
								Name: "platform",
								Type: "string",
								Help: "Set platform if server is multi-platform capable.",
							},
							{
								Name:    "quiet",
								Type:    "bool",
								Aliases: []string{"q"},
								Help:    "Suppress verbose output.",
							},
							{
								Name:       "image",
								Type:       "string",
								Help:       "Image name to pull.",
								Required:   true,
								Positional: 1,
							},
						},
					},
					{
						Name: "tag",
						Path: "/image/tag",
						Help: "RunImageTag tags an image into a repository.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := image.TagArgs{}

							if p := cmd.Get("references"); p != nil && p.Value != nil {
								s.References = p.Value.([]string)
							}

							err := errors.Join((image.RunTag)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/image/tag")
							ctx = context.WithValue(ctx, cli.Args("/image/tag"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:       "references",
								Type:       "[]string",
								Help:       "Source and target image references.",
								Positional: 2,
							},
						},
					},
					{
						Name: "rm",
						Path: "/image/rm",
						Help: "RunImageRm removes images.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := image.RmArgs{}

							if p := cmd.Get("force"); p != nil && p.Value != nil {
								s.Force = p.Value.(bool)
							}

							if p := cmd.Get("no-prune"); p != nil && p.Value != nil {
								s.NoPrune = p.Value.(bool)
							}

							if p := cmd.Get("images"); p != nil && p.Value != nil {
								s.Images = p.Value.([]string)
							}

							err := errors.Join((image.RunRm)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/image/rm")
							ctx = context.WithValue(ctx, cli.Args("/image/rm"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "force",
								Type:    "bool",
								Aliases: []string{"f"},
								Help:    "Force removal of the image.",
							},
							{
								Name: "no-prune",
								Type: "bool",
								Help: "Do not delete untagged parents.",
							},
							{
								Name:       "images",
								Type:       "[]string",
								Help:       "Image references to remove.",
								Required:   true,
								Positional: -1,
							},
						},
					},
				},
			},
			{
				Name: "container",
				Path: "/container",
				Help: "Manage containers",
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {

					ctx = context.WithValue(ctx, cli.Parent{}, "/container")
					return ctx, nil
				},
				Commands: []*cli.Command{
					{
						Name: "ls",
						Path: "/container/ls",
						Help: "RunContainerLs lists containers.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := container.LsArgs{}

							if p := cmd.Get("all"); p != nil && p.Value != nil {
								s.All = p.Value.(bool)
							}

							if p := cmd.Get("filter"); p != nil && p.Value != nil {
								s.Filter = p.Value.([]string)
							}

							if p := cmd.Get("format"); p != nil && p.Value != nil {
								s.Format = p.Value.(string)
							}

							if p := cmd.Get("last"); p != nil && p.Value != nil {
								s.Last = p.Value.(int)
							}

							if p := cmd.Get("quiet"); p != nil && p.Value != nil {
								s.Quiet = p.Value.(bool)
							}

							if p := cmd.Get("size"); p != nil && p.Value != nil {
								s.Size = p.Value.(bool)
							}

							err := errors.Join((container.RunLs)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/container/ls")
							ctx = context.WithValue(ctx, cli.Args("/container/ls"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "all",
								Type:    "bool",
								Aliases: []string{"a"},
								Help:    "Show all containers.",
							},
							{
								Name:    "filter",
								Type:    "[]string",
								Aliases: []string{"f"},
								Help:    "Provide filter values.",
							},
							{
								Name: "format",
								Type: "string",
								Help: "Pretty-print containers using a Go template.",
							},
							{
								Name:    "last",
								Type:    "int",
								Aliases: []string{"n"},
								Help:    "Show n last created containers.",
							},
							{
								Name:    "quiet",
								Type:    "bool",
								Aliases: []string{"q"},
								Help:    "Only display container IDs.",
							},
							{
								Name: "size",
								Type: "bool",
								Help: "Display total file sizes.",
							},
						},
					},
					{
						Name: "run",
						Path: "/container/run",
						Help: "RunContainerRun runs a command in a new container.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := container.RunArgs{}

							if p := cmd.Get("detach"); p != nil && p.Value != nil {
								s.Detach = p.Value.(bool)
							}

							if p := cmd.Get("env"); p != nil && p.Value != nil {
								s.Env = p.Value.([]string)
							}

							if p := cmd.Get("env-file"); p != nil && p.Value != nil {
								s.EnvFile = p.Value.([]string)
							}

							if p := cmd.Get("interactive"); p != nil && p.Value != nil {
								s.Interactive = p.Value.(bool)
							}

							if p := cmd.Get("name"); p != nil && p.Value != nil {
								s.Name = p.Value.(string)
							}

							if p := cmd.Get("publish"); p != nil && p.Value != nil {
								s.Publish = p.Value.([]string)
							}

							if p := cmd.Get("rm"); p != nil && p.Value != nil {
								s.Rm = p.Value.(bool)
							}

							if p := cmd.Get("pull"); p != nil && p.Value != nil {
								s.Pull = p.Value.(string)
							}

							if p := cmd.Get("tty"); p != nil && p.Value != nil {
								s.Tty = p.Value.(bool)
							}

							if p := cmd.Get("volume"); p != nil && p.Value != nil {
								s.Volume = p.Value.([]string)
							}

							if p := cmd.Get("workdir"); p != nil && p.Value != nil {
								s.Workdir = p.Value.(string)
							}

							if p := cmd.Get("image"); p != nil && p.Value != nil {
								s.Image = p.Value.(string)
							}

							if p := cmd.Get("command"); p != nil && p.Value != nil {
								s.Command = p.Value.([]string)
							}

							err := errors.Join((container.RunRun)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/container/run")
							ctx = context.WithValue(ctx, cli.Args("/container/run"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "detach",
								Type:    "bool",
								Aliases: []string{"d"},
								Help:    "Run container in background and print container ID.",
							},
							{
								Name:    "env",
								Type:    "[]string",
								Aliases: []string{"e"},
								Help:    "Set environment variables.",
							},
							{
								Name: "env-file",
								Type: "[]string",
								Help: "Read in a file of environment variables.",
								Labels: map[string][]string{
									"path": {
										"exists",
										"file",
									},
								},
								Validate: cli.PathValidate,
							},
							{
								Name:    "interactive",
								Type:    "bool",
								Aliases: []string{"i"},
								Help:    "Keep STDIN open even if not attached.",
							},
							{
								Name: "name",
								Type: "string",
								Help: "Assign a name to the container.",
							},
							{
								Name:    "publish",
								Type:    "[]string",
								Aliases: []string{"p"},
								Help:    "Publish a container's port to the host.",
							},
							{
								Name: "rm",
								Type: "bool",
								Help: "Automatically remove the container when it exits.",
							},
							{
								Name: "pull",
								Type: "string",
								Help: "Pull image before running.",
								Defaults: []string{
									"missing",
								},
								Choices: []string{
									"always",
									"missing",
									"never",
								},
								Validate: cli.EnumValidate,
							},
							{
								Name:    "tty",
								Type:    "bool",
								Aliases: []string{"t"},
								Help:    "Allocate a pseudo-TTY.",
							},
							{
								Name:    "volume",
								Type:    "[]string",
								Aliases: []string{"v"},
								Help:    "Bind mount a volume.",
							},
							{
								Name:    "workdir",
								Type:    "string",
								Aliases: []string{"w"},
								Help:    "Working directory inside the container.",
							},
							{
								Name:       "image",
								Type:       "string",
								Help:       "Image to run.",
								Required:   true,
								Positional: 1,
							},
							{
								Name:       "command",
								Type:       "[]string",
								Help:       "Command and arguments to execute.",
								Positional: -1,
							},
						},
					},
					{
						Name: "logs",
						Path: "/container/logs",
						Help: "RunContainerLogs fetches container logs.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := container.LogsArgs{}

							if p := cmd.Get("follow"); p != nil && p.Value != nil {
								s.Follow = p.Value.(bool)
							}

							if p := cmd.Get("since"); p != nil && p.Value != nil {
								s.Since = p.Value.(string)
							}

							if p := cmd.Get("tail"); p != nil && p.Value != nil {
								s.Tail = p.Value.(string)
							}

							if p := cmd.Get("timestamps"); p != nil && p.Value != nil {
								s.Timestamps = p.Value.(bool)
							}

							if p := cmd.Get("container"); p != nil && p.Value != nil {
								s.Container = p.Value.(string)
							}

							err := errors.Join((container.RunLogs)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/container/logs")
							ctx = context.WithValue(ctx, cli.Args("/container/logs"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "follow",
								Type:    "bool",
								Aliases: []string{"f"},
								Help:    "Follow log output.",
							},
							{
								Name: "since",
								Type: "string",
								Help: "Show logs since timestamp or relative duration.",
							},
							{
								Name: "tail",
								Type: "string",
								Help: "Number of lines to show from the end of the logs.",
								Defaults: []string{
									"all",
								},
							},
							{
								Name:    "timestamps",
								Type:    "bool",
								Aliases: []string{"t"},
								Help:    "Show timestamps.",
							},
							{
								Name:       "container",
								Type:       "string",
								Help:       "Container name or ID.",
								Required:   true,
								Positional: 1,
							},
						},
					},
					{
						Name: "rm",
						Path: "/container/rm",
						Help: "RunContainerRm removes containers.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := container.RmArgs{}

							if p := cmd.Get("force"); p != nil && p.Value != nil {
								s.Force = p.Value.(bool)
							}

							if p := cmd.Get("volumes"); p != nil && p.Value != nil {
								s.Volumes = p.Value.(bool)
							}

							if p := cmd.Get("containers"); p != nil && p.Value != nil {
								s.Containers = p.Value.([]string)
							}

							err := errors.Join((container.RunRm)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/container/rm")
							ctx = context.WithValue(ctx, cli.Args("/container/rm"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "force",
								Type:    "bool",
								Aliases: []string{"f"},
								Help:    "Force removal of a running container.",
							},
							{
								Name:    "volumes",
								Type:    "bool",
								Aliases: []string{"v"},
								Help:    "Remove anonymous volumes associated with the container.",
							},
							{
								Name:       "containers",
								Type:       "[]string",
								Help:       "Container names or IDs.",
								Required:   true,
								Positional: -1,
							},
						},
					},
				},
			},
			{
				Name: "network",
				Path: "/network",
				Help: "Manage networks",
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {

					ctx = context.WithValue(ctx, cli.Parent{}, "/network")
					return ctx, nil
				},
				Commands: []*cli.Command{
					{
						Name: "ls",
						Path: "/network/ls",
						Help: "RunNetworkLs lists networks.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := network.LsArgs{}

							if p := cmd.Get("filter"); p != nil && p.Value != nil {
								s.Filter = p.Value.([]string)
							}

							if p := cmd.Get("format"); p != nil && p.Value != nil {
								s.Format = p.Value.(string)
							}

							if p := cmd.Get("quiet"); p != nil && p.Value != nil {
								s.Quiet = p.Value.(bool)
							}

							err := errors.Join((network.RunLs)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/network/ls")
							ctx = context.WithValue(ctx, cli.Args("/network/ls"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "filter",
								Type:    "[]string",
								Aliases: []string{"f"},
								Help:    "Provide filter values.",
							},
							{
								Name: "format",
								Type: "string",
								Help: "Pretty-print networks using a Go template.",
							},
							{
								Name:    "quiet",
								Type:    "bool",
								Aliases: []string{"q"},
								Help:    "Only display network IDs.",
							},
						},
					},
					{
						Name: "create",
						Path: "/network/create",
						Help: "RunNetworkCreate creates a network.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := network.CreateArgs{}

							if p := cmd.Get("driver"); p != nil && p.Value != nil {
								s.Driver = p.Value.(string)
							}

							if p := cmd.Get("label"); p != nil && p.Value != nil {
								s.Label = p.Value.([]string)
							}

							if p := cmd.Get("internal"); p != nil && p.Value != nil {
								s.Internal = p.Value.(bool)
							}

							if p := cmd.Get("gateway-mac"); p != nil && p.Value != nil {
								s.GatewayMAC = p.Value.(net.HardwareAddr)
							}

							if p := cmd.Get("subnet"); p != nil && p.Value != nil {
								s.Subnet = p.Value.(net.IPNet)
							}

							if p := cmd.Get("ip-range"); p != nil && p.Value != nil {
								s.IPRange = p.Value.(net.IPNet)
							}

							if p := cmd.Get("name"); p != nil && p.Value != nil {
								s.Name = p.Value.(string)
							}

							err := errors.Join((network.RunCreate)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/network/create")
							ctx = context.WithValue(ctx, cli.Args("/network/create"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name: "driver",
								Type: "string",
								Help: "Driver to manage the network.",
								Defaults: []string{
									"bridge",
								},
							},
							{
								Name:    "label",
								Type:    "[]string",
								Aliases: []string{"l"},
								Help:    "Set metadata on the network.",
							},
							{
								Name: "internal",
								Type: "bool",
								Help: "Restrict external access to the network.",
							},
							{
								Name: "gateway-mac",
								Type: "net.HardwareAddr",
								Help: "Assign a preferred MAC address to the network gateway.",
							},
							{
								Name: "subnet",
								Type: "net.IPNet",
								Help: "Allocate addresses from this subnet.",
							},
							{
								Name: "ip-range",
								Type: "net.IPNet",
								Help: "Restrict dynamic allocation to this subrange.",
							},
							{
								Name:       "name",
								Type:       "string",
								Help:       "Network name.",
								Required:   true,
								Positional: 1,
							},
						},
					},
					{
						Name: "rm",
						Path: "/network/rm",
						Help: "RunNetworkRm removes networks.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := network.RmArgs{}

							if p := cmd.Get("networks"); p != nil && p.Value != nil {
								s.Networks = p.Value.([]string)
							}

							err := errors.Join((network.RunRm)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/network/rm")
							ctx = context.WithValue(ctx, cli.Args("/network/rm"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:       "networks",
								Type:       "[]string",
								Help:       "Networks to remove.",
								Required:   true,
								Positional: -1,
							},
						},
					},
				},
			},
			{
				Name: "volume",
				Path: "/volume",
				Help: "Manage volumes",
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {

					ctx = context.WithValue(ctx, cli.Parent{}, "/volume")
					return ctx, nil
				},
				Commands: []*cli.Command{
					{
						Name: "ls",
						Path: "/volume/ls",
						Help: "RunVolumeLs lists volumes.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := volume.LsArgs{}

							if p := cmd.Get("filter"); p != nil && p.Value != nil {
								s.Filter = p.Value.([]string)
							}

							if p := cmd.Get("format"); p != nil && p.Value != nil {
								s.Format = p.Value.(string)
							}

							if p := cmd.Get("quiet"); p != nil && p.Value != nil {
								s.Quiet = p.Value.(bool)
							}

							err := errors.Join((volume.RunLs)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/volume/ls")
							ctx = context.WithValue(ctx, cli.Args("/volume/ls"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "filter",
								Type:    "[]string",
								Aliases: []string{"f"},
								Help:    "Provide filter values.",
							},
							{
								Name: "format",
								Type: "string",
								Help: "Pretty-print volumes using a Go template.",
							},
							{
								Name:    "quiet",
								Type:    "bool",
								Aliases: []string{"q"},
								Help:    "Only display volume names.",
							},
						},
					},
					{
						Name: "create",
						Path: "/volume/create",
						Help: "RunVolumeCreate creates a volume.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := volume.CreateArgs{}

							if p := cmd.Get("driver"); p != nil && p.Value != nil {
								s.Driver = p.Value.(string)
							}

							if p := cmd.Get("label"); p != nil && p.Value != nil {
								s.Label = p.Value.([]string)
							}

							if p := cmd.Get("name"); p != nil && p.Value != nil {
								s.Name = p.Value.(string)
							}

							err := errors.Join((volume.RunCreate)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/volume/create")
							ctx = context.WithValue(ctx, cli.Args("/volume/create"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name: "driver",
								Type: "string",
								Help: "Driver to manage the volume.",
								Defaults: []string{
									"local",
								},
							},
							{
								Name:    "label",
								Type:    "[]string",
								Aliases: []string{"l"},
								Help:    "Set metadata on the volume.",
							},
							{
								Name:       "name",
								Type:       "string",
								Help:       "Volume name.",
								Positional: 1,
							},
						},
					},
					{
						Name: "rm",
						Path: "/volume/rm",
						Help: "RunVolumeRm removes volumes.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := volume.RmArgs{}

							if p := cmd.Get("force"); p != nil && p.Value != nil {
								s.Force = p.Value.(bool)
							}

							if p := cmd.Get("volumes"); p != nil && p.Value != nil {
								s.Volumes = p.Value.([]string)
							}

							err := errors.Join((volume.RunRm)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/volume/rm")
							ctx = context.WithValue(ctx, cli.Args("/volume/rm"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "force",
								Type:    "bool",
								Aliases: []string{"f"},
								Help:    "Force removal of the volume.",
							},
							{
								Name:       "volumes",
								Type:       "[]string",
								Help:       "Volume names.",
								Required:   true,
								Positional: -1,
							},
						},
					},
				},
			},
			{
				Name: "system",
				Path: "/system",
				Help: "Manage Docker",
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {

					ctx = context.WithValue(ctx, cli.Parent{}, "/system")
					return ctx, nil
				},
				Commands: []*cli.Command{
					{
						Name: "prune",
						Path: "/system/prune",
						Help: "RunSystemPrune removes unused data.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := SystemPruneArgs{}

							if p := cmd.Get("all"); p != nil && p.Value != nil {
								s.All = p.Value.(bool)
							}

							if p := cmd.Get("filter"); p != nil && p.Value != nil {
								s.Filter = p.Value.([]string)
							}

							if p := cmd.Get("force"); p != nil && p.Value != nil {
								s.Force = p.Value.(bool)
							}

							if p := cmd.Get("volumes"); p != nil && p.Value != nil {
								s.Volumes = p.Value.(bool)
							}

							err := errors.Join((RunSystemPrune)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/system/prune")
							ctx = context.WithValue(ctx, cli.Args("/system/prune"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "all",
								Type:    "bool",
								Aliases: []string{"a"},
								Help:    "Remove all unused images, not just dangling ones.",
							},
							{
								Name: "filter",
								Type: "[]string",
								Help: "Provide filter values.",
							},
							{
								Name:    "force",
								Type:    "bool",
								Aliases: []string{"f"},
								Help:    "Do not prompt for confirmation.",
							},
							{
								Name: "volumes",
								Type: "bool",
								Help: "Prune anonymous volumes.",
							},
						},
					},
				},
			},
			{
				Name: "version",
				Path: "/version",
				Help: "RunVersion shows the Docker version information.",
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
					s := VersionArgs{}

					if p := cmd.Get("format"); p != nil && p.Value != nil {
						s.Format = p.Value.(string)
					}

					err := errors.Join((RunVersion)(ctx, s), cmd.Cleanup())
					if err != nil {
						return ctx, err
					}

					ctx = context.WithValue(ctx, cli.Parent{}, "/version")
					ctx = context.WithValue(ctx, cli.Args("/version"), s)
					return ctx, nil
				},
				Args: []*cli.Arg{
					{
						Name: "format",
						Type: "string",
						Help: "Format the output using the given Go template.",
					},
				},
			},
		},
	}

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	if last := cmds[len(cmds)-1]; len(last.Commands) > 0 {
		return cmds, cli.ErrHelp
	}

	for _, cmd := range cmds {
		if cmd.Invoke == nil {
			continue
		}
		ctx, err = cmd.Invoke(ctx, cmd)
		if err != nil {
			return cmds, err
		}
	}

	return cmds, nil
}
