// Code generated by gocli DO NOT EDIT

package main

import (
	"context"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) error {
	root := cli.Command{
		Path: "/",
		Commands: []*cli.Command{
			{
				Name: "login",
				Path: "/login",
			},
			{
				Name: "logout",
				Path: "/logout",
			},
		},
	}

	cmds, err := root.Parse(args)
	if err != nil {
		return err
	}

	for _, cmd := range cmds {
		switch cmd.Path {
		case "/":
			f := cmd.Handler.(func(context.Context) error)
			if err := f(ctx); err != nil {
				return err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
		case "/login":
			f := cmd.Handler.(func(context.Context) error)
			if err := f(ctx); err != nil {
				return err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/login")
		case "/logout":
			f := cmd.Handler.(func(context.Context) error)
			if err := f(ctx); err != nil {
				return err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/logout")
		}
	}

	return nil
}
