// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"
	"io"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path: "/",
		Help: "Output the first part of files",
		Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
			s := (NewArgs)()

			if p := cmd.Get("bytes"); p != nil && p.Value != nil {
				s.Bytes = p.Value.(uint)
			}

			if p := cmd.Get("lines"); p != nil && p.Value != nil {
				s.Lines = p.Value.(uint)
			}

			if p := cmd.Get("quiet"); p != nil && p.Value != nil {
				s.Quiet = p.Value.(bool)
			}

			if p := cmd.Get("verbose"); p != nil && p.Value != nil {
				s.Verbose = p.Value.(bool)
			}

			if p := cmd.Get("files"); p != nil && p.Value != nil {
				s.Files = p.Value.([]io.Reader)
			}

			err := errors.Join((RunHead)(ctx, s), cmd.Cleanup())
			if err != nil {
				return ctx, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			ctx = context.WithValue(ctx, cli.Args("/"), s)
			return ctx, nil
		},
		Args: []*cli.Arg{
			{
				Name:    "bytes",
				Type:    "uint",
				Aliases: []string{"c"},
				Help:    "Print the first NUM bytes of each file.",
			},
			{
				Name:    "lines",
				Type:    "uint",
				Aliases: []string{"n"},
				Help:    "Print the first NUM lines instead of the first 10.",
				Defaults: []string{
					"10",
				},
			},
			{
				Name:    "quiet",
				Type:    "bool",
				Aliases: []string{"q"},
				Help:    "Never print headers with file names.",
			},
			{
				Name:    "verbose",
				Type:    "bool",
				Aliases: []string{"v"},
				Help:    "Always print headers with file names.",
			},
			{
				Name:       "files",
				Type:       "[]io.Reader",
				Help:       "Files to read. Reads standard input when omitted.",
				Positional: -1,
			},
		},
	}

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		if cmd.Invoke == nil {
			continue
		}
		ctx, err = cmd.Invoke(ctx, cmd)
		if err != nil {
			return cmds, err
		}
	}

	return cmds, nil
}
