package main

import (
	"fmt"
	"io"
	"os"
	"strings"

	"golang.org/x/tools/imports"
)

func (gen *Generator) Generate(filename string) error {
	w := &strings.Builder{}

	fmt.Fprintln(w, "// Code generated by cligen DO NOT EDIT")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package main")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "import (")

	for i := range gen.Imports {
		fmt.Fprintf(w, "%q\n", i)
	}

	fmt.Fprintln(w, ")")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "func init() {")

	for _, cmd := range gen.Cmds {
		fmt.Fprintf(w, "%s.Register(invoke%s)\n", cmd.ID, cmd.ID)
	}

	fmt.Fprintln(w, "}")

	for _, cmd := range gen.Cmds {
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "func invoke%s(ctx context.Context, args []string) ([]*cli.Command, error) {\n", cmd.ID)
		fmt.Fprintln(w, "root := cli.Command{")

		gen.generateCommand(w, cmd)

		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "cmds, err := root.Parse(args)")
		fmt.Fprintln(w, "if err != nil {")
		fmt.Fprintln(w, "return cmds, err")
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "for _, cmd := range cmds {")
		fmt.Fprintln(w, "switch cmd.Path {")

		for _, c := range cmd.CommandList() {
			fmt.Fprintf(w, "case %q:\n", c.Path)

			if c.Handler != "" {
				if c.Struct == "" {
					fmt.Fprintln(w, "f := cmd.Handler.(func(context.Context) error)")
					fmt.Fprintln(w, "if err := f(ctx); err != nil {")
					fmt.Fprintln(w, "return cmds, err")
					fmt.Fprintln(w, "}")
				} else {
					if c.New != "" {
						fmt.Fprintf(w, "s := cmd.New.(func() %s)()\n", c.Struct)
					} else {
						fmt.Fprintf(w, "s := %s{}\n", c.Struct)
					}

					for _, arg := range c.Args {
						fmt.Fprintln(w, "")
						fmt.Fprintf(w, "if p := cmd.Get(%q); p != nil && p.Value != nil {\n", arg.Flag)
						fmt.Fprintf(w, "s.%s = p.Value.(%s)\n", arg.Name, arg.Type)
						fmt.Fprintln(w, "}")
					}

					fmt.Fprintln(w, "")
					fmt.Fprintf(w, "f := cmd.Handler.(func(context.Context, %s) error)\n", c.Struct)
					fmt.Fprintln(w, "if err := f(ctx, s); err != nil {")
					fmt.Fprintln(w, "return cmds, err")
					fmt.Fprintln(w, "}")
				}
			}

			fmt.Fprintln(w, "")
			fmt.Fprintf(w, "ctx = context.WithValue(ctx, cli.Parent{}, %q)\n", c.Path)
			if c.Struct != "" {
				fmt.Fprintf(w, "ctx = context.WithValue(ctx, cli.Args(%q), s)\n", c.Path)
			}
		}

		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "\treturn cmds, nil")
		fmt.Fprintln(w, "}")
	}

	// p := []byte(w.String())

	p, err := imports.Process(filename, []byte(w.String()), nil)
	if err != nil {
		return err
	}

	return os.WriteFile(filename, p, 0644)
}

func (gen *Generator) generateCommand(w io.Writer, cmd *Command) {
	if cmd.Name != "" {
		fmt.Fprintf(w, "Name: %q,\n", cmd.Name)
	}

	fmt.Fprintf(w, "Path: %q,\n", cmd.Path)

	if len(cmd.Aliases) != 0 {
		fmt.Fprintf(w, "Aliases: %#v,\n", cmd.Aliases)
	}

	if cmd.Handler != "" {
		fmt.Fprintf(w, "Handler: %s,\n", cmd.Handler)
	}

	if cmd.New != "" {
		fmt.Fprintf(w, "New: %s,\n", cmd.New)
	}

	help := cmd.Help

	if help == "" {
		help = cmd.Doc
	}

	if help != "" {
		fmt.Fprintf(w, "Help: %q,\n", help)
	}

	if len(cmd.Args) != 0 {
		fmt.Fprintln(w, "Args: []*cli.Arg{")

		for _, arg := range cmd.Args {
			fmt.Fprintln(w, "{")
			fmt.Fprintf(w, "Name:%q,\n", arg.Flag)
			fmt.Fprintf(w, "Type:%q,\n", arg.Type)

			if len(arg.Aliases) != 0 {
				fmt.Fprintf(w, "Aliases:%#v,\n", arg.Aliases)
			}

			if !arg.Native() {
				s := strings.TrimPrefix(arg.Type, "[]")

				fmt.Fprintln(w, "Parse: func(s string) (any, error) {")
				fmt.Fprintf(w, "var v %s\n", s)
				fmt.Fprintln(w, "return v, any(&v).(encoding.TextUnmarshaler).UnmarshalText([]byte(s))")
				fmt.Fprintln(w, "},")
			}

			help := arg.Help

			if help == "" {
				help = arg.Doc
			}

			if help != "" {
				fmt.Fprintf(w, "Help: %q,\n", help)
			}

			if arg.Default != "" {
				fmt.Fprintf(w, "Default: %q,\n", arg.Default)
			}

			if arg.Required {
				fmt.Fprintln(w, "Required: true,")
			}

			if arg.Positional != 0 {
				fmt.Fprintf(w, "Positional: %d,\n", arg.Positional)
			}

			fmt.Fprintln(w, "},")
		}

		fmt.Fprintln(w, "},")
	}

	if len(cmd.Commands) != 0 {
		fmt.Fprintln(w, "Commands: []*cli.Command{")

		for _, c := range cmd.Commands {
			fmt.Fprintln(w, "{")
			gen.generateCommand(w, c)
			fmt.Fprintln(w, "},")
		}

		fmt.Fprintln(w, "},")
	}
}
