package main

import (
	"fmt"
	"os"
	"strings"

	"golang.org/x/tools/imports"
)

func (gen *Generator) Generate(filename string) error {
	w := &strings.Builder{}

	fmt.Fprintln(w, "// Code generated by cligen DO NOT EDIT")
	fmt.Fprintln(w, "")
	fmt.Fprintf(w, "package %s\n", gen.Package)
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "import (")

	for path, alias := range gen.Imports {
		if alias != "" {
			fmt.Fprintf(w, "%s %q\n", alias, path)
			continue
		}

		fmt.Fprintf(w, "%q\n", path)
	}

	fmt.Fprintln(w, ")")

	for _, cmd := range gen.Cmds {
		for _, c := range cmd.CommandList() {
			if c.Struct == "" || len(c.Commands) == 0 {
				continue
			}

			fmt.Fprintln(w, "")
			fmt.Fprintf(w, "func %sFrom(ctx context.Context) %s {\n", c.Struct, c.Struct)
			fmt.Fprintf(w, "return ctx.Value(cli.Args(%q)).(%s)\n", c.Path, c.Struct)
			fmt.Fprintln(w, "}")
		}
	}

	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "func init() {")

	for _, cmd := range gen.Cmds {
		fmt.Fprintf(w, "%s.Register(invoke%s)\n", cmd.ID, cmd.ID)
	}

	fmt.Fprintln(w, "}")

	if _, ok := gen.Providers["aws"]; ok {
		gen.generateAWSResolvers(w)
	}

	for _, cmd := range gen.Cmds {
		if err := gen.generateInvoke(w, cmd); err != nil {
			return err
		}
	}

	p, err := imports.Process(filename, []byte(w.String()), nil)
	if err != nil {
		return err
	}

	return os.WriteFile(filename, p, 0644)
}

func (gen *Generator) generateInvoke(w *strings.Builder, cmd *Command) error {
	fmt.Fprintln(w, "")
	fmt.Fprintf(w, "func invoke%s(ctx context.Context, args []string) ([]*cli.Command, error) {\n", cmd.ID)
	fmt.Fprintln(w, "root := cli.Command{")

	if err := gen.generateCommand(w, cmd); err != nil {
		return err
	}

	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "")
	if _, ok := gen.Providers["aws"]; ok {
		gen.generateProviderHooks(w)
	}
	fmt.Fprintln(w, "cmds, err := root.Parse(ctx, args)")
	fmt.Fprintln(w, "if err != nil {")
	fmt.Fprintln(w, "return cmds, err")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "")

	if len(cmd.Commands) > 0 {
		fmt.Fprintln(w, "if last := cmds[len(cmds)-1]; len(last.Commands) > 0 {")
		fmt.Fprintln(w, "return cmds, cli.ErrHelp")
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
	}

	fmt.Fprintln(w, "for _, cmd := range cmds {")
	fmt.Fprintln(w, "if cmd.Invoke == nil {")
	fmt.Fprintln(w, "continue")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "ctx, err = cmd.Invoke(ctx, cmd)")
	fmt.Fprintln(w, "if err != nil {")
	fmt.Fprintln(w, "return cmds, err")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "\treturn cmds, nil")
	fmt.Fprintln(w, "}")
	return nil
}

func (gen *Generator) generateProviderHooks(w *strings.Builder) {
	fmt.Fprintln(w, "for _, cmd := range root.CommandList() {")
	fmt.Fprintln(w, "if cmd.Lookup != nil {")
	fmt.Fprintln(w, "prevLookup := cmd.Lookup")
	fmt.Fprintln(w, "cmd.Lookup = func(ctx context.Context, arg *cli.Arg, value string) (string, bool, error) {")
	fmt.Fprintln(w, "if resolved, ok, err := prevLookup(ctx, arg, value); ok || err != nil {")
	fmt.Fprintln(w, "return resolved, ok, err")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "return resolveNativeValue(ctx, arg, value)")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "} else {")
	fmt.Fprintln(w, "cmd.Lookup = resolveNativeValue")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "if cmd.Open != nil {")
	fmt.Fprintln(w, "prevOpen := cmd.Open")
	fmt.Fprintln(w, "cmd.Open = func(ctx context.Context, arg *cli.Arg, value string) (io.Reader, bool, error) {")
	fmt.Fprintln(w, "if reader, ok, err := prevOpen(ctx, arg, value); ok || err != nil {")
	fmt.Fprintln(w, "return reader, ok, err")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "return resolveNativeReader(ctx, arg, value)")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "} else {")
	fmt.Fprintln(w, "cmd.Open = resolveNativeReader")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "}")
}
