package main

import (
	"fmt"
	"io"
)

func (gen *Generator) generateAWSResolvers(w io.Writer) {
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "func resolveNativeValue(ctx context.Context, arg *cli.Arg, value string) (string, bool, error) {")
	fmt.Fprintln(w, `rest, ok := strings.CutPrefix(value, "@aws:")`)
	fmt.Fprintln(w, "if !ok {")
	fmt.Fprintln(w, "return value, false, nil")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, `kind, name, ok := strings.Cut(rest, ":")`)
	fmt.Fprintln(w, `if !ok || name == "" {`)
	fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: invalid AWS native value %q", arg.Name, value)`)
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "cfg, err := config.LoadDefaultConfig(ctx)")
	fmt.Fprintln(w, "if err != nil {")
	fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: load AWS config: %w", arg.Name, err)`)
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "switch kind {")
	fmt.Fprintln(w, `case "ssm":`)
	fmt.Fprintln(w, "resp, err := ssm.NewFromConfig(cfg).GetParameter(ctx, &ssm.GetParameterInput{")
	fmt.Fprintln(w, "Name:           aws.String(name),")
	fmt.Fprintln(w, "WithDecryption: aws.Bool(true),")
	fmt.Fprintln(w, "})")
	fmt.Fprintln(w, "if err != nil {")
	fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: resolve %q: %w", arg.Name, value, err)`)
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "if resp.Parameter == nil || resp.Parameter.Value == nil {")
	fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: resolve %q: empty parameter value", arg.Name, value)`)
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "return *resp.Parameter.Value, true, nil")
	fmt.Fprintln(w, `case "secret":`)
	fmt.Fprintln(w, "resp, err := secretsmanager.NewFromConfig(cfg).GetSecretValue(ctx, &secretsmanager.GetSecretValueInput{")
	fmt.Fprintln(w, "SecretId: aws.String(name),")
	fmt.Fprintln(w, "})")
	fmt.Fprintln(w, "if err != nil {")
	fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: resolve %q: %w", arg.Name, value, err)`)
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "if resp.SecretString == nil {")
	fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: resolve %q: secret string is empty", arg.Name, value)`)
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "return *resp.SecretString, true, nil")
	fmt.Fprintln(w, "default:")
	fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: unsupported AWS native value %q", arg.Name, value)`)
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "func resolveNativeReader(ctx context.Context, arg *cli.Arg, value string) (io.Reader, bool, error) {")
	fmt.Fprintln(w, "u, err := url.Parse(value)")
	fmt.Fprintln(w, "if err != nil {")
	fmt.Fprintln(w, "return nil, false, nil")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, `if u.Scheme != "s3" {`)
	fmt.Fprintln(w, "return nil, false, nil")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, `if u.Host == "" || strings.TrimPrefix(u.Path, "/") == "" {`)
	fmt.Fprintf(w, "%s\n", `return nil, true, fmt.Errorf("%s: invalid S3 URI %q", arg.Name, value)`)
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "cfg, err := config.LoadDefaultConfig(ctx)")
	fmt.Fprintln(w, "if err != nil {")
	fmt.Fprintf(w, "%s\n", `return nil, true, fmt.Errorf("%s: load AWS config: %w", arg.Name, err)`)
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "resp, err := s3.NewFromConfig(cfg, func(o *s3.Options) {")
	fmt.Fprintln(w, "o.DisableLogOutputChecksumValidationSkipped = true")
	fmt.Fprintln(w, "}).GetObject(ctx, &s3.GetObjectInput{")
	fmt.Fprintln(w, "Bucket: aws.String(u.Host),")
	fmt.Fprintln(w, "Key: aws.String(strings.TrimPrefix(u.Path, \"/\")),")
	fmt.Fprintln(w, "})")
	fmt.Fprintln(w, "if err != nil {")
	fmt.Fprintln(w, "resp, err = s3.NewFromConfig(cfg, func(o *s3.Options) {")
	fmt.Fprintln(w, "o.Credentials = aws.AnonymousCredentials{}")
	fmt.Fprintln(w, "o.DisableLogOutputChecksumValidationSkipped = true")
	fmt.Fprintln(w, "}).GetObject(ctx, &s3.GetObjectInput{")
	fmt.Fprintln(w, "Bucket: aws.String(u.Host),")
	fmt.Fprintln(w, "Key: aws.String(strings.TrimPrefix(u.Path, \"/\")),")
	fmt.Fprintln(w, "})")
	fmt.Fprintln(w, "if err != nil {")
	fmt.Fprintf(w, "%s\n", `return nil, true, fmt.Errorf("%s: resolve %q: %w", arg.Name, value, err)`)
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w, "return resp.Body, true, nil")
	fmt.Fprintln(w, "}")
}
