package main

import (
	"fmt"
	"io"
	"os"
	"slices"
	"strings"

	"golang.org/x/tools/imports"
)

func (gen *Generator) Generate(filename string) error {
	w := &strings.Builder{}

	fmt.Fprintln(w, "// Code generated by cligen DO NOT EDIT")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "package main")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "import (")

	for i := range gen.Imports {
		fmt.Fprintf(w, "%q\n", i)
	}

	fmt.Fprintln(w, ")")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "func init() {")

	for _, cmd := range gen.Cmds {
		fmt.Fprintf(w, "%s.Register(invoke%s)\n", cmd.ID, cmd.ID)
	}

	fmt.Fprintln(w, "}")

	if gen.hasNativeResolvers() {
		gen.generateNativeResolvers(w)
	}

	for _, cmd := range gen.Cmds {
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "func invoke%s(ctx context.Context, args []string) ([]*cli.Command, error) {\n", cmd.ID)
		fmt.Fprintln(w, "root := cli.Command{")

		gen.generateCommand(w, cmd)

		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
		if gen.hasNativeResolvers() {
			fmt.Fprintln(w, "if root.Resolve != nil {")
			fmt.Fprintln(w, "prevResolve := root.Resolve")
			fmt.Fprintln(w, "root.Resolve = func(ctx context.Context, arg *cli.Arg, value string) (string, bool, error) {")
			fmt.Fprintln(w, "if resolved, ok, err := prevResolve(ctx, arg, value); ok || err != nil {")
			fmt.Fprintln(w, "return resolved, ok, err")
			fmt.Fprintln(w, "}")
			fmt.Fprintln(w, "return resolveNativeValue(ctx, arg, value)")
			fmt.Fprintln(w, "}")
			fmt.Fprintln(w, "} else {")
			fmt.Fprintln(w, "root.Resolve = resolveNativeValue")
			fmt.Fprintln(w, "}")
		}
		fmt.Fprintln(w, "cmds, err := root.Parse(ctx, args)")
		fmt.Fprintln(w, "if err != nil {")
		fmt.Fprintln(w, "return cmds, err")
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "for _, cmd := range cmds {")
		fmt.Fprintln(w, "switch cmd.Path {")

		for _, c := range cmd.CommandList() {
			fmt.Fprintf(w, "case %q:\n", c.Path)

			if c.Handler != "" {
				if c.Struct == "" {
					fmt.Fprintln(w, "f := cmd.Handler.(func(context.Context) error)")
					fmt.Fprintln(w, "if err := f(ctx); err != nil {")
					fmt.Fprintln(w, "return cmds, err")
					fmt.Fprintln(w, "}")
				} else {
					if c.New != "" {
						fmt.Fprintf(w, "s := cmd.New.(func() %s)()\n", c.Struct)
					} else {
						fmt.Fprintf(w, "s := %s{}\n", c.Struct)
					}

					for _, arg := range c.Args {
						fmt.Fprintln(w, "")
						fmt.Fprintf(w, "if p := cmd.Get(%q); p != nil && p.Value != nil {\n", arg.Flag)
						fmt.Fprintf(w, "s.%s = p.Value.(%s)\n", arg.Name, arg.Type)
						fmt.Fprintln(w, "}")
					}

					fmt.Fprintln(w, "")
					fmt.Fprintf(w, "f := cmd.Handler.(func(context.Context, %s) error)\n", c.Struct)
					fmt.Fprintln(w, "if err := f(ctx, s); err != nil {")
					fmt.Fprintln(w, "return cmds, err")
					fmt.Fprintln(w, "}")
				}
			}

			fmt.Fprintln(w, "")
			fmt.Fprintf(w, "ctx = context.WithValue(ctx, cli.Parent{}, %q)\n", c.Path)
			if c.Struct != "" {
				fmt.Fprintf(w, "ctx = context.WithValue(ctx, cli.Args(%q), s)\n", c.Path)
			}
		}

		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "\treturn cmds, nil")
		fmt.Fprintln(w, "}")
	}

	// p := []byte(w.String())

	p, err := imports.Process(filename, []byte(w.String()), nil)
	if err != nil {
		return err
	}

	return os.WriteFile(filename, p, 0644)
}

func (gen *Generator) hasNativeResolvers() bool {
	return len(gen.Providers) != 0
}

func (gen *Generator) generateNativeResolvers(w io.Writer) {
	if _, ok := gen.Providers["aws"]; ok {
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "func resolveNativeValue(ctx context.Context, arg *cli.Arg, value string) (string, bool, error) {")
		fmt.Fprintln(w, `if !strings.HasPrefix(value, "@aws:") {`)
		fmt.Fprintln(w, "return value, false, nil")
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, `kind, name, ok := strings.Cut(strings.TrimPrefix(value, "@aws:"), ":")`)
		fmt.Fprintln(w, `if !ok || name == "" {`)
		fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: invalid AWS native value %q", arg.Name, value)`)
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "cfg, err := config.LoadDefaultConfig(ctx)")
		fmt.Fprintln(w, "if err != nil {")
		fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: load AWS config: %w", arg.Name, err)`)
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "switch kind {")
		fmt.Fprintln(w, `case "ssm":`)
		fmt.Fprintln(w, "resp, err := ssm.NewFromConfig(cfg).GetParameter(ctx, &ssm.GetParameterInput{")
		fmt.Fprintln(w, "Name:           aws.String(name),")
		fmt.Fprintln(w, "WithDecryption: aws.Bool(true),")
		fmt.Fprintln(w, "})")
		fmt.Fprintln(w, "if err != nil {")
		fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: resolve %q: %w", arg.Name, value, err)`)
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "if resp.Parameter == nil || resp.Parameter.Value == nil {")
		fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: resolve %q: empty parameter value", arg.Name, value)`)
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "return *resp.Parameter.Value, true, nil")
		fmt.Fprintln(w, `case "secret":`)
		fmt.Fprintln(w, "resp, err := secretsmanager.NewFromConfig(cfg).GetSecretValue(ctx, &secretsmanager.GetSecretValueInput{")
		fmt.Fprintln(w, "SecretId: aws.String(name),")
		fmt.Fprintln(w, "})")
		fmt.Fprintln(w, "if err != nil {")
		fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: resolve %q: %w", arg.Name, value, err)`)
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "if resp.SecretString == nil {")
		fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: resolve %q: secret string is empty", arg.Name, value)`)
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "return *resp.SecretString, true, nil")
		fmt.Fprintln(w, "default:")
		fmt.Fprintf(w, "%s\n", `return "", true, fmt.Errorf("%s: unsupported AWS native value %q", arg.Name, value)`)
		fmt.Fprintln(w, "}")
		fmt.Fprintln(w, "}")
	}
}

func (gen *Generator) generateCommand(w io.Writer, cmd *Command) {
	if cmd.Name != "" {
		fmt.Fprintf(w, "Name: %q,\n", cmd.Name)
	}

	fmt.Fprintf(w, "Path: %q,\n", cmd.Path)

	if len(cmd.Aliases) != 0 {
		fmt.Fprintf(w, "Aliases: %#v,\n", cmd.Aliases)
	}

	if cmd.Handler != "" {
		fmt.Fprintf(w, "Handler: %s,\n", cmd.Handler)
	}

	if cmd.New != "" {
		fmt.Fprintf(w, "New: %s,\n", cmd.New)
	}

	if cmd.Resolve != "" {
		fmt.Fprintf(w, "Resolve: %s,\n", cmd.Resolve)
	}

	help := cmd.Help

	if help == "" {
		help = cmd.Doc
	}

	if help != "" {
		fmt.Fprintf(w, "Help: %q,\n", help)
	}

	if len(cmd.Args) != 0 {
		fmt.Fprintln(w, "Args: []*cli.Arg{")

		for _, arg := range cmd.Args {
			fmt.Fprintln(w, "{")
			fmt.Fprintf(w, "Name:%q,\n", arg.Flag)
			fmt.Fprintf(w, "Type:%q,\n", arg.Type)

			if len(arg.Aliases) != 0 {
				fmt.Fprintf(w, "Aliases:%#v,\n", arg.Aliases)
			}

			if !arg.Native() {
				s := strings.TrimPrefix(arg.Type, "[]")

				fmt.Fprintln(w, "Parse: func(s string) (any, error) {")
				fmt.Fprintf(w, "var v %s\n", s)
				fmt.Fprintln(w, "return v, any(&v).(encoding.TextUnmarshaler).UnmarshalText([]byte(s))")
				fmt.Fprintln(w, "},")
			}

			help := arg.Help

			if help == "" {
				help = arg.Doc
			}

			if help != "" {
				fmt.Fprintf(w, "Help: %q,\n", help)
			}

			switch len(arg.Defaults) {
			case 0:
			case 1:
				fmt.Fprintf(w, "Default: %q,\n", arg.Defaults[0])
			default:
				fmt.Fprintln(w, "Defaults: []string{")

				for _, s := range arg.Defaults {
					fmt.Fprintf(w, "%q,\n", s)
				}

				fmt.Fprintln(w, "},")
			}

			if len(arg.Labels) != 0 {
				keys := make([]string, 0, len(arg.Labels))
				for key := range arg.Labels {
					keys = append(keys, key)
				}
				slices.Sort(keys)

				fmt.Fprintln(w, "Labels: map[string][]string{")
				for _, key := range keys {
					fmt.Fprintf(w, "%q: []string{\n", key)
					for _, value := range arg.Labels[key] {
						fmt.Fprintf(w, "%q,\n", value)
					}
					fmt.Fprintln(w, "},")
				}
				fmt.Fprintln(w, "},")
			}

			if arg.Validate != "" {
				fmt.Fprintf(w, "Validate: %s,\n", arg.Validate)
			}

			if arg.Required {
				fmt.Fprintln(w, "Required: true,")
			}

			if arg.Positional != 0 {
				fmt.Fprintf(w, "Positional: %d,\n", arg.Positional)
			}

			fmt.Fprintln(w, "},")
		}

		fmt.Fprintln(w, "},")
	}

	if len(cmd.Commands) != 0 {
		fmt.Fprintln(w, "Commands: []*cli.Command{")

		for _, c := range cmd.Commands {
			fmt.Fprintln(w, "{")
			gen.generateCommand(w, c)
			fmt.Fprintln(w, "},")
		}

		fmt.Fprintln(w, "},")
	}
}
