// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path:    "/",
		Handler: Run,
		Help:    "Run generates the CLI glue for the requested source file.",
		Args: []*cli.Arg{
			{
				Name:    "source",
				Type:    "string",
				Help:    "Location of the source file with the cli.Command definition.",
				Default: "$GOFILE",
				Labels: map[string][]string{
					"path": []string{
						"exists",
						"file",
						".go",
					},
				},
				Validate: cli.PathValidate,
				Required: true,
			},
			{
				Name: "output",
				Type: "string",
				Help: "Output file. Defaults to the source file with a .cli.go suffix.",
			},
			{
				Name: "provider",
				Type: "[]string",
				Help: "Native value resolver provider to include in generated code.",
			},
		},
	}

	root.AddBuiltins()

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		switch cmd.Path {
		case "/version":
			f := cmd.Handler.(func(context.Context) error)
			err := errors.Join(f(ctx), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}
		case "/":
			s := Args{}

			if p := cmd.Get("source"); p != nil && p.Value != nil {
				s.Source = p.Value.(string)
			}

			if p := cmd.Get("output"); p != nil && p.Value != nil {
				s.Output = p.Value.(string)
			}

			if p := cmd.Get("provider"); p != nil && p.Value != nil {
				s.Provider = p.Value.([]string)
			}

			f := cmd.Handler.(func(context.Context, Args) error)
			err := errors.Join(f(ctx, s), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			ctx = context.WithValue(ctx, cli.Args("/"), s)
		}
	}

	return cmds, nil
}
