// Code generated by cligen DO NOT EDIT

package main

import (
	"context"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path:    "/",
		Handler: Search,
		Help:    "Simple version of grep",
		Args: []*cli.Arg{
			{
				Name:       "pattern",
				Type:       "string",
				Help:       "Pattern to search for.",
				Required:   true,
				Positional: 1,
			},
			{
				Name:       "paths",
				Type:       "[]string",
				Help:       "Files or directories to search in.",
				Positional: -1,
			},
			{
				Name:    "ignore-case",
				Type:    "bool",
				Aliases: []string{"i"},
				Help:    "Match case-insensitively.",
			},
			{
				Name:    "invert-match",
				Type:    "bool",
				Aliases: []string{"v"},
				Help:    "Search for pattern that do not match instead.",
			},
			{
				Name:    "recursive",
				Type:    "bool",
				Aliases: []string{"R", "r"},
				Help:    "Search recursively in directories.",
			},
			{
				Name:    "max-count",
				Type:    "uint",
				Aliases: []string{"m"},
				Help:    "Stop after this many matches.",
				Default: "10",
			},
		},
	}

	cmds, err := root.Parse(args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		switch cmd.Path {
		case "/":
			s := Args{}

			if p := cmd.Get("pattern"); p != nil && p.Value != nil {
				s.Pattern = p.Value.(string)
			}

			if p := cmd.Get("paths"); p != nil && p.Value != nil {
				s.Paths = p.Value.([]string)
			}

			if p := cmd.Get("ignore-case"); p != nil && p.Value != nil {
				s.IgnoreCase = p.Value.(bool)
			}

			if p := cmd.Get("invert-match"); p != nil && p.Value != nil {
				s.InvertMatch = p.Value.(bool)
			}

			if p := cmd.Get("recursive"); p != nil && p.Value != nil {
				s.Recursive = p.Value.(bool)
			}

			if p := cmd.Get("max-count"); p != nil && p.Value != nil {
				s.MaxCount = p.Value.(uint)
			}

			f := cmd.Handler.(func(context.Context, Args) error)
			if err := f(ctx, s); err != nil {
				return cmds, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			ctx = context.WithValue(ctx, cli.Args("/"), s)
		}
	}

	return cmds, nil
}
