// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path: "/",
		Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			return ctx, nil
		},
		Commands: []*cli.Command{
			{
				Name: "login",
				Path: "/login",
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
					s := LoginArgs{}

					if p := cmd.Get("user"); p != nil && p.Value != nil {
						s.User = p.Value.(string)
					}

					if p := cmd.Get("password"); p != nil && p.Value != nil {
						s.Password = p.Value.(string)
					}

					err := errors.Join((RunLogin)(ctx, s), cmd.Cleanup())
					if err != nil {
						return ctx, err
					}

					ctx = context.WithValue(ctx, cli.Parent{}, "/login")
					ctx = context.WithValue(ctx, cli.Args("/login"), s)
					return ctx, nil
				},
				Args: []*cli.Arg{
					{
						Name: "user",
						Type: "string",
					},
					{
						Name: "password",
						Type: "string",
					},
				},
			},
			{
				Name:    "logout",
				Path:    "/logout",
				Aliases: []string{"signout"},
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {

					err := errors.Join((RunLogout)(ctx), cmd.Cleanup())
					if err != nil {
						return ctx, err
					}

					ctx = context.WithValue(ctx, cli.Parent{}, "/logout")
					return ctx, nil
				},
			},
		},
	}

	root.AddBuiltins()

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	if last := cmds[len(cmds)-1]; len(last.Commands) > 0 {
		return cmds, cli.ErrHelp
	}

	for _, cmd := range cmds {
		if cmd.Invoke == nil {
			continue
		}
		ctx, err = cmd.Invoke(ctx, cmd)
		if err != nil {
			return cmds, err
		}
	}

	return cmds, nil
}
