// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path: "/",
		Commands: []*cli.Command{
			{
				Name:    "login",
				Path:    "/login",
				Handler: RunLogin,
				Args: []*cli.Arg{
					{
						Name: "user",
						Type: "string",
					},
					{
						Name: "password",
						Type: "string",
					},
				},
			},
			{
				Name:    "logout",
				Path:    "/logout",
				Aliases: []string{"signout"},
				Handler: RunLogout,
			},
		},
	}

	root.AddBuiltins()

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		switch cmd.Path {
		case "/version":
			f := cmd.Handler.(func(context.Context) error)
			err := errors.Join(f(ctx), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}
		case "/":

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
		case "/login":
			s := LoginArgs{}

			if p := cmd.Get("user"); p != nil && p.Value != nil {
				s.User = p.Value.(string)
			}

			if p := cmd.Get("password"); p != nil && p.Value != nil {
				s.Password = p.Value.(string)
			}

			f := cmd.Handler.(func(context.Context, LoginArgs) error)
			err := errors.Join(f(ctx, s), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/login")
			ctx = context.WithValue(ctx, cli.Args("/login"), s)
		case "/logout":
			f := cmd.Handler.(func(context.Context) error)
			err := errors.Join(f(ctx), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/logout")
		}
	}

	return cmds, nil
}
