// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path:    "/",
		Handler: RunPercentile,
		Help:    "Report percentiles from a set of samples",
		Args: []*cli.Arg{
			{
				Name:    "scale",
				Type:    "float32",
				Help:    "Multiply each sample by this scale factor before reporting.",
				Default: "1",
			},
			{
				Name:    "percentiles",
				Type:    "[]float64",
				Help:    "Percentiles to report.",
				Default: "50,95,99",
			},
			{
				Name:       "samples",
				Type:       "[]float64",
				Help:       "Samples to summarize.",
				Required:   true,
				Positional: -1,
			},
		},
	}

	root.AddBuiltins()

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		switch cmd.Path {
		case "/version":
			f := cmd.Handler.(func(context.Context) error)
			err := errors.Join(f(ctx), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}
		case "/":
			s := Args{}

			if p := cmd.Get("scale"); p != nil && p.Value != nil {
				s.Scale = p.Value.(float32)
			}

			if p := cmd.Get("percentiles"); p != nil && p.Value != nil {
				s.Percentiles = p.Value.([]float64)
			}

			if p := cmd.Get("samples"); p != nil && p.Value != nil {
				s.Samples = p.Value.([]float64)
			}

			f := cmd.Handler.(func(context.Context, Args) error)
			err := errors.Join(f(ctx, s), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			ctx = context.WithValue(ctx, cli.Args("/"), s)
		}
	}

	return cmds, nil
}
