// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/url"
	"strings"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	"github.com/aws/aws-sdk-go-v2/service/ssm"
	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func resolveNativeValue(ctx context.Context, arg *cli.Arg, value string) (string, bool, error) {
	rest, ok := strings.CutPrefix(value, "@aws:")
	if !ok {
		return value, false, nil
	}

	kind, name, ok := strings.Cut(rest, ":")
	if !ok || name == "" {
		return "", true, fmt.Errorf("%s: invalid AWS native value %q", arg.Name, value)
	}

	cfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		return "", true, fmt.Errorf("%s: load AWS config: %w", arg.Name, err)
	}

	switch kind {
	case "ssm":
		resp, err := ssm.NewFromConfig(cfg).GetParameter(ctx, &ssm.GetParameterInput{
			Name:           aws.String(name),
			WithDecryption: aws.Bool(true),
		})
		if err != nil {
			return "", true, fmt.Errorf("%s: resolve %q: %w", arg.Name, value, err)
		}
		if resp.Parameter == nil || resp.Parameter.Value == nil {
			return "", true, fmt.Errorf("%s: resolve %q: empty parameter value", arg.Name, value)
		}
		return *resp.Parameter.Value, true, nil
	case "secret":
		resp, err := secretsmanager.NewFromConfig(cfg).GetSecretValue(ctx, &secretsmanager.GetSecretValueInput{
			SecretId: aws.String(name),
		})
		if err != nil {
			return "", true, fmt.Errorf("%s: resolve %q: %w", arg.Name, value, err)
		}
		if resp.SecretString == nil {
			return "", true, fmt.Errorf("%s: resolve %q: secret string is empty", arg.Name, value)
		}
		return *resp.SecretString, true, nil
	default:
		return "", true, fmt.Errorf("%s: unsupported AWS native value %q", arg.Name, value)
	}
}

func resolveNativeReader(ctx context.Context, arg *cli.Arg, value string) (io.Reader, bool, error) {
	u, err := url.Parse(value)
	if err != nil {
		return nil, false, nil
	}
	if u.Scheme != "s3" {
		return nil, false, nil
	}
	if u.Host == "" || strings.TrimPrefix(u.Path, "/") == "" {
		return nil, true, fmt.Errorf("%s: invalid S3 URI %q", arg.Name, value)
	}

	cfg, err := config.LoadDefaultConfig(ctx)
	if err != nil {
		return nil, true, fmt.Errorf("%s: load AWS config: %w", arg.Name, err)
	}

	resp, err := s3.NewFromConfig(cfg, func(o *s3.Options) {
		o.DisableLogOutputChecksumValidationSkipped = true
	}).GetObject(ctx, &s3.GetObjectInput{
		Bucket: aws.String(u.Host),
		Key:    aws.String(strings.TrimPrefix(u.Path, "/")),
	})
	if err != nil {
		resp, err = s3.NewFromConfig(cfg, func(o *s3.Options) {
			o.Credentials = aws.AnonymousCredentials{}
			o.DisableLogOutputChecksumValidationSkipped = true
		}).GetObject(ctx, &s3.GetObjectInput{
			Bucket: aws.String(u.Host),
			Key:    aws.String(strings.TrimPrefix(u.Path, "/")),
		})
		if err != nil {
			return nil, true, fmt.Errorf("%s: resolve %q: %w", arg.Name, value, err)
		}
	}
	return resp.Body, true, nil
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path: "/",
		Help: "Print the contents of HTTP or S3 objects",
		Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
			s := Args{}

			if p := cmd.Get("files"); p != nil && p.Value != nil {
				s.Files = p.Value.([]io.Reader)
			}

			err := errors.Join((RunCat)(ctx, s), cmd.Cleanup())
			if err != nil {
				return ctx, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			ctx = context.WithValue(ctx, cli.Args("/"), s)
			return ctx, nil
		},
		Args: []*cli.Arg{
			{
				Name:       "files",
				Type:       "[]io.Reader",
				Help:       "Files to print.",
				Required:   true,
				Positional: -1,
			},
		},
	}

	for _, cmd := range root.CommandList() {
		if cmd.Lookup != nil {
			prevLookup := cmd.Lookup
			cmd.Lookup = func(ctx context.Context, arg *cli.Arg, value string) (string, bool, error) {
				if resolved, ok, err := prevLookup(ctx, arg, value); ok || err != nil {
					return resolved, ok, err
				}
				return resolveNativeValue(ctx, arg, value)
			}
		} else {
			cmd.Lookup = resolveNativeValue
		}
		if cmd.Open != nil {
			prevOpen := cmd.Open
			cmd.Open = func(ctx context.Context, arg *cli.Arg, value string) (io.Reader, bool, error) {
				if reader, ok, err := prevOpen(ctx, arg, value); ok || err != nil {
					return reader, ok, err
				}
				return resolveNativeReader(ctx, arg, value)
			}
		} else {
			cmd.Open = resolveNativeReader
		}
	}
	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		if cmd.Invoke == nil {
			continue
		}
		ctx, err = cmd.Invoke(ctx, cmd)
		if err != nil {
			return cmds, err
		}
	}

	return cmds, nil
}
