// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path: "/",
		Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			return ctx, nil
		},
		Commands: []*cli.Command{
			{
				Name:     "serve",
				Path:     "/serve",
				Help:     "Run the HTTP server",
				Template: "{{define \"argDetail\"}}{{.Help}} ({{.Type}}{{if .Default}}, default: {{.Default}}{{else if .Defaults}}, default: {{range $i, $default := .Defaults}}{{if $i}} | {{end}}{{$default}}{{end}}{{end}}{{if .Choices}}, choices: {{range $i, $choice := .Choices}}{{if $i}}, {{end}}{{$choice}}{{end}}{{end}}{{if .Labels}}, labels: {{range $i, $label := .Labels}}{{if $i}}, {{end}}{{$label}}{{end}}{{end}}){{end}}{{.Usage}}{{if .Command.Help}}\n\n{{.Command.Help}}{{end}}{{if .Current.Options}}\n\nOptions:\n{{range $i, $arg := .Current.Options}}{{if $i}}{{\"\\n\"}}{{end}}{{printf \"  --%-14s \" .Name}}{{template \"argDetail\" .}}{{end}}{{end}}\n\nRoutes:\n  GET /healthz\n  GET /readyz\n",
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
					s := cli.ServeHTTPArgs{}

					if p := cmd.Get("addr"); p != nil && p.Value != nil {
						s.Addr = p.Value.(string)
					}

					err := errors.Join((cli.MakeServeHTTP(Mux))(ctx, s), cmd.Cleanup())
					if err != nil {
						return ctx, err
					}

					ctx = context.WithValue(ctx, cli.Parent{}, "/serve")
					ctx = context.WithValue(ctx, cli.Args("/serve"), s)
					return ctx, nil
				},
				Args: []*cli.Arg{
					{
						Name:    "addr",
						Type:    "string",
						Help:    "Address to listen on.",
						Default: "127.0.0.1:8080",
					},
				},
			},
		},
	}

	root.AddBuiltins()

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	if last := cmds[len(cmds)-1]; len(last.Commands) > 0 {
		return cmds, cli.ErrHelp
	}

	for _, cmd := range cmds {
		if cmd.Invoke == nil {
			continue
		}
		ctx, err = cmd.Invoke(ctx, cmd)
		if err != nil {
			return cmds, err
		}
	}

	return cmds, nil
}
