// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path: "/",
		Help: "Synchronize a working tree into a release directory",
		Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
			s := Args{}

			if p := cmd.Get("worktree"); p != nil && p.Value != nil {
				s.Worktree = p.Value.(string)
			}

			if p := cmd.Get("workers"); p != nil && p.Value != nil {
				s.Workers = p.Value.(int)
			}

			if p := cmd.Get("retries"); p != nil && p.Value != nil {
				s.Retries = p.Value.(uint8)
			}

			if p := cmd.Get("priority"); p != nil && p.Value != nil {
				s.Priority = p.Value.(int8)
			}

			if p := cmd.Get("scratch"); p != nil && p.Value != nil {
				s.Scratch = p.Value.(string)
			}

			if p := cmd.Get("state"); p != nil && p.Value != nil {
				s.State = p.Value.(string)
			}

			if p := cmd.Get("helper"); p != nil && p.Value != nil {
				s.Helper = p.Value.(string)
			}

			if p := cmd.Get("lock"); p != nil && p.Value != nil {
				s.Lock = p.Value.(string)
			}

			if p := cmd.Get("current"); p != nil && p.Value != nil {
				s.Current = p.Value.(string)
			}

			if p := cmd.Get("sources"); p != nil && p.Value != nil {
				s.Sources = p.Value.([]string)
			}

			if p := cmd.Get("destination"); p != nil && p.Value != nil {
				s.Destination = p.Value.(string)
			}

			err := errors.Join((RunSync)(ctx, s), cmd.Cleanup())
			if err != nil {
				return ctx, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			ctx = context.WithValue(ctx, cli.Args("/"), s)
			return ctx, nil
		},
		Args: []*cli.Arg{
			{
				Name: "worktree",
				Type: "string",
				Help: "Root directory containing the files to sync.",
				Labels: map[string][]string{
					"path": {
						"exists",
						"dir",
					},
				},
				Validate: cli.PathValidate,
			},
			{
				Name: "workers",
				Type: "int",
				Help: "Number of concurrent copy workers.",
			},
			{
				Name: "retries",
				Type: "uint8",
				Help: "Retry failed copies this many times.",
			},
			{
				Name: "priority",
				Type: "int8",
				Help: "Lower values run helper work sooner.",
			},
			{
				Name: "scratch",
				Type: "string",
				Help: "Empty scratch directory used while staging the release.",
				Labels: map[string][]string{
					"path": {
						"exists",
						"dir",
						"empty",
					},
				},
				Validate: cli.PathValidate,
			},
			{
				Name: "state",
				Type: "string",
				Help: "Existing state file to update while the sync runs.",
				Labels: map[string][]string{
					"path": {
						"exists",
					},
				},
				Validate: cli.PathValidate,
			},
			{
				Name: "helper",
				Type: "string",
				Help: "Helper program used to post-process copied files.",
				Labels: map[string][]string{
					"path": {
						"exec",
					},
				},
				Validate: cli.PathValidate,
			},
			{
				Name: "lock",
				Type: "string",
				Help: "Lock file path reserved for the next sync run.",
				Labels: map[string][]string{
					"path": {
						"not-exists",
					},
				},
				Validate: cli.PathValidate,
			},
			{
				Name: "current",
				Type: "string",
				Help: "Symlink pointing at the current release.",
				Labels: map[string][]string{
					"path": {
						"symlink",
					},
				},
				Validate: cli.PathValidate,
			},
			{
				Name:       "sources",
				Type:       "[]string",
				Help:       "Source patterns to include in the sync.",
				Positional: -1,
			},
			{
				Name:       "destination",
				Type:       "string",
				Help:       "Destination directory name for the staged release.",
				Required:   true,
				Positional: 1,
			},
		},
	}

	root.AddBuiltins()

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		if cmd.Invoke == nil {
			continue
		}
		ctx, err = cmd.Invoke(ctx, cmd)
		if err != nil {
			return cmds, err
		}
	}

	return cmds, nil
}
