// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path:    "/",
		Handler: Run,
		Help:    "Run a command",
		Args: []*cli.Arg{
			{
				Name: "some-flag",
				Type: "string",
				Help: "SomeFlag is a flag argument.",
			},
		},
	}

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		switch cmd.Path {
		case "/":
			s := Args{}

			if p := cmd.Get("some-flag"); p != nil && p.Value != nil {
				s.SomeFlag = p.Value.(string)
			}

			f := cmd.Handler.(func(context.Context, Args) error)
			err := errors.Join(f(ctx, s), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			ctx = context.WithValue(ctx, cli.Args("/"), s)
		}
	}

	return cmds, nil
}
