// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path:    "/",
		Handler: RunCopy,
		Help:    "Copy files and directories",
		Args: []*cli.Arg{
			{
				Name:    "archive",
				Type:    "bool",
				Aliases: []string{"a"},
				Help:    "Preserve mode, ownership, and timestamps when possible.",
			},
			{
				Name:    "force",
				Type:    "bool",
				Aliases: []string{"f"},
				Help:    "Overwrite destination files without prompting.",
			},
			{
				Name:    "interactive",
				Type:    "bool",
				Aliases: []string{"i"},
				Help:    "Prompt before overwrite.",
			},
			{
				Name:    "recursive",
				Type:    "bool",
				Aliases: []string{"R", "r"},
				Help:    "Copy directories recursively.",
			},
			{
				Name: "manifest",
				Type: "string",
				Help: "Write a JSON manifest describing the copy plan.",
				Labels: map[string][]string{
					"path": []string{
						"abs",
						".json",
					},
				},
				Validate: func(arg *cli.Arg, s string) error {
					if err := cli.PathValidate(arg, s); err != nil {
						return err
					}
					return nil
				},
			},
			{
				Name: "sources",
				Type: "[]string",
				Help: "Source paths to copy.",
				Labels: map[string][]string{
					"path": []string{
						"rel",
						"glob",
					},
				},
				Validate: func(arg *cli.Arg, s string) error {
					if err := cli.PathValidate(arg, s); err != nil {
						return err
					}
					return nil
				},
				Positional: -1,
			},
			{
				Name: "destination",
				Type: "string",
				Help: "Destination path.",
				Labels: map[string][]string{
					"path": []string{
						"rel",
						"mkdir",
					},
				},
				Validate: func(arg *cli.Arg, s string) error {
					if err := cli.PathValidate(arg, s); err != nil {
						return err
					}
					return nil
				},
				Required:   true,
				Positional: 1,
			},
		},
	}

	root.AddBuiltins()

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		switch cmd.Path {
		case "/version":
			f := cmd.Handler.(func(context.Context) error)
			err := errors.Join(f(ctx), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}
		case "/":
			s := Args{}

			if p := cmd.Get("archive"); p != nil && p.Value != nil {
				s.Archive = p.Value.(bool)
			}

			if p := cmd.Get("force"); p != nil && p.Value != nil {
				s.Force = p.Value.(bool)
			}

			if p := cmd.Get("interactive"); p != nil && p.Value != nil {
				s.Interactive = p.Value.(bool)
			}

			if p := cmd.Get("recursive"); p != nil && p.Value != nil {
				s.Recursive = p.Value.(bool)
			}

			if p := cmd.Get("manifest"); p != nil && p.Value != nil {
				s.Manifest = p.Value.(string)
			}

			if p := cmd.Get("sources"); p != nil && p.Value != nil {
				s.Sources = p.Value.([]string)
			}

			if p := cmd.Get("destination"); p != nil && p.Value != nil {
				s.Destination = p.Value.(string)
			}

			f := cmd.Handler.(func(context.Context, Args) error)
			err := errors.Join(f(ctx, s), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			ctx = context.WithValue(ctx, cli.Args("/"), s)
		}
	}

	return cmds, nil
}
