// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"encoding"
	"errors"
	"net/mail"
	"net/url"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path: "/",
		Help: "Fast, scalable, distributed revision control system",
		Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			return ctx, nil
		},
		Commands: []*cli.Command{
			{
				Name: "commit",
				Path: "/commit",
				Help: "RunCommit creates a new commit.",
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
					s := CommitArgs{}

					if p := cmd.Get("all"); p != nil && p.Value != nil {
						s.All = p.Value.(bool)
					}

					if p := cmd.Get("amend"); p != nil && p.Value != nil {
						s.Amend = p.Value.(bool)
					}

					if p := cmd.Get("cleanup"); p != nil && p.Value != nil {
						s.Cleanup = p.Value.(CleanupMode)
					}

					if p := cmd.Get("author"); p != nil && p.Value != nil {
						s.Author = p.Value.(mail.Address)
					}

					if p := cmd.Get("message"); p != nil && p.Value != nil {
						s.Message = p.Value.(string)
					}

					if p := cmd.Get("signoff"); p != nil && p.Value != nil {
						s.Signoff = p.Value.(bool)
					}

					if p := cmd.Get("scope"); p != nil && p.Value != nil {
						s.Scope = p.Value.(string)
					}

					if p := cmd.Get("template"); p != nil && p.Value != nil {
						s.Template = p.Value.(string)
					}

					if p := cmd.Get("paths"); p != nil && p.Value != nil {
						s.Paths = p.Value.([]string)
					}

					err := errors.Join((RunCommit)(ctx, s), cmd.Cleanup())
					if err != nil {
						return ctx, err
					}

					ctx = context.WithValue(ctx, cli.Parent{}, "/commit")
					ctx = context.WithValue(ctx, cli.Args("/commit"), s)
					return ctx, nil
				},
				Args: []*cli.Arg{
					{
						Name:    "all",
						Type:    "bool",
						Aliases: []string{"a"},
						Help:    "Automatically stage tracked files that have been modified and deleted.",
					},
					{
						Name: "amend",
						Type: "bool",
						Help: "Replace the tip of the current branch by creating a new commit.",
					},
					{
						Name: "cleanup",
						Type: "CleanupMode",
						Parse: func(s string) (any, error) {
							var v CleanupMode
							return v, any(&v).(encoding.TextUnmarshaler).UnmarshalText([]byte(s))
						},
						Help: "Determine how the commit message is cleaned up.",
						Defaults: []string{
							"strip",
						},
						Choices: cli.EnumChoices(func() any {
							var v CleanupMode
							return &v
						}()),
						Validate: cli.EnumValidate,
					},
					{
						Name: "author",
						Type: "mail.Address",
						Help: "Override the commit author.",
					},
					{
						Name:    "message",
						Type:    "string",
						Aliases: []string{"m"},
						Help:    "Use the given message as the commit message.",
						Defaults: []string{
							"$GIT_MESSAGE",
							"@COMMIT_EDITMSG",
						},
						DefaultsOptional: []bool{true, false},
					},
					{
						Name:    "signoff",
						Type:    "bool",
						Aliases: []string{"s"},
						Help:    "Add a Signed-off-by trailer.",
					},
					{
						Name: "scope",
						Type: "string",
						Help: "Prefix for the commit scope.",
						Defaults: []string{
							"$GIT_SCOPE/commit",
						},
						DefaultsOptional: []bool{true},
					},
					{
						Name: "template",
						Type: "string",
						Help: "Use this template file when preparing the message.",
						Labels: map[string][]string{
							"path": {
								"exists",
								"file",
								"clean",
							},
						},
						Validate: cli.PathValidate,
					},
					{
						Name:       "paths",
						Type:       "[]string",
						Help:       "Update the index before committing these paths.",
						Positional: -1,
					},
				},
			},
			{
				Name: "remote",
				Path: "/remote",
				Help: "Manage set of tracked repositories",
				Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {

					ctx = context.WithValue(ctx, cli.Parent{}, "/remote")
					return ctx, nil
				},
				Commands: []*cli.Command{
					{
						Name: "add",
						Path: "/remote/add",
						Help: "RunRemoteAdd adds a new remote.",
						Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
							s := RemoteAddArgs{}

							if p := cmd.Get("fetch"); p != nil && p.Value != nil {
								s.Fetch = p.Value.(bool)
							}

							if p := cmd.Get("name"); p != nil && p.Value != nil {
								s.Name = p.Value.(string)
							}

							if p := cmd.Get("url"); p != nil && p.Value != nil {
								s.URL = p.Value.(url.URL)
							}

							err := errors.Join((RunRemoteAdd)(ctx, s), cmd.Cleanup())
							if err != nil {
								return ctx, err
							}

							ctx = context.WithValue(ctx, cli.Parent{}, "/remote/add")
							ctx = context.WithValue(ctx, cli.Args("/remote/add"), s)
							return ctx, nil
						},
						Args: []*cli.Arg{
							{
								Name:    "fetch",
								Type:    "bool",
								Aliases: []string{"f"},
								Help:    "Fetch the remote branches immediately after adding the remote.",
							},
							{
								Name:       "name",
								Type:       "string",
								Help:       "Name of the new remote.",
								Required:   true,
								Positional: 1,
							},
							{
								Name:       "url",
								Type:       "url.URL",
								Help:       "URL of the remote repository.",
								Required:   true,
								Positional: 1,
							},
						},
					},
				},
			},
		},
	}

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	if last := cmds[len(cmds)-1]; len(last.Commands) > 0 {
		return cmds, cli.ErrHelp
	}

	for _, cmd := range cmds {
		if cmd.Invoke == nil {
			continue
		}
		ctx, err = cmd.Invoke(ctx, cmd)
		if err != nil {
			return cmds, err
		}
	}

	return cmds, nil
}
