// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"encoding"
	"errors"
	"net/mail"
	"net/url"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path: "/",
		Help: "Fast, scalable, distributed revision control system",
		Commands: []*cli.Command{
			{
				Name:    "commit",
				Path:    "/commit",
				Handler: RunCommit,
				Help:    "RunCommit creates a new commit.",
				Args: []*cli.Arg{
					{
						Name:    "all",
						Type:    "bool",
						Aliases: []string{"a"},
						Help:    "Automatically stage tracked files that have been modified and deleted.",
					},
					{
						Name: "amend",
						Type: "bool",
						Help: "Replace the tip of the current branch by creating a new commit.",
					},
					{
						Name: "cleanup",
						Type: "CleanupMode",
						Parse: func(s string) (any, error) {
							var v CleanupMode
							return v, any(&v).(encoding.TextUnmarshaler).UnmarshalText([]byte(s))
						},
						Help:    "Determine how the commit message is cleaned up.",
						Default: "strip",
						Choices: cli.EnumChoices(func() any {
							var v CleanupMode
							return &v
						}()),
						Validate: func(arg *cli.Arg, s string) error {
							if err := cli.EnumValidate(arg, s); err != nil {
								return err
							}
							return nil
						},
					},
					{
						Name: "author",
						Type: "mail.Address",
						Help: "Override the commit author.",
					},
					{
						Name:    "message",
						Type:    "string",
						Aliases: []string{"m"},
						Help:    "Use the given message as the commit message.",
						Defaults: []string{
							"$GIT_MESSAGE",
							"@COMMIT_EDITMSG",
						},
					},
					{
						Name:    "signoff",
						Type:    "bool",
						Aliases: []string{"s"},
						Help:    "Add a Signed-off-by trailer.",
					},
					{
						Name: "template",
						Type: "string",
						Help: "Use this template file when preparing the message.",
						Labels: map[string][]string{
							"path": []string{
								"exists",
								"file",
								"readable",
								"clean",
							},
						},
						Validate: func(arg *cli.Arg, s string) error {
							if err := cli.PathValidate(arg, s); err != nil {
								return err
							}
							return nil
						},
					},
					{
						Name:       "paths",
						Type:       "[]string",
						Help:       "Update the index before committing these paths.",
						Positional: -1,
					},
				},
			},
			{
				Name: "remote",
				Path: "/remote",
				Help: "Manage set of tracked repositories",
				Commands: []*cli.Command{
					{
						Name:    "add",
						Path:    "/remote/add",
						Handler: RunRemoteAdd,
						Help:    "RunRemoteAdd adds a new remote.",
						Args: []*cli.Arg{
							{
								Name:    "fetch",
								Type:    "bool",
								Aliases: []string{"f"},
								Help:    "Fetch the remote branches immediately after adding the remote.",
							},
							{
								Name:       "name",
								Type:       "string",
								Help:       "Name of the new remote.",
								Required:   true,
								Positional: 1,
							},
							{
								Name:       "url",
								Type:       "url.URL",
								Help:       "URL of the remote repository.",
								Required:   true,
								Positional: 1,
							},
						},
					},
				},
			},
		},
	}

	root.AddBuiltins()

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		switch cmd.Path {
		case "/version":
			f := cmd.Handler.(func(context.Context) error)
			err := errors.Join(f(ctx), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}
		case "/":

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
		case "/commit":
			s := CommitArgs{}

			if p := cmd.Get("all"); p != nil && p.Value != nil {
				s.All = p.Value.(bool)
			}

			if p := cmd.Get("amend"); p != nil && p.Value != nil {
				s.Amend = p.Value.(bool)
			}

			if p := cmd.Get("cleanup"); p != nil && p.Value != nil {
				s.Cleanup = p.Value.(CleanupMode)
			}

			if p := cmd.Get("author"); p != nil && p.Value != nil {
				s.Author = p.Value.(mail.Address)
			}

			if p := cmd.Get("message"); p != nil && p.Value != nil {
				s.Message = p.Value.(string)
			}

			if p := cmd.Get("signoff"); p != nil && p.Value != nil {
				s.Signoff = p.Value.(bool)
			}

			if p := cmd.Get("template"); p != nil && p.Value != nil {
				s.Template = p.Value.(string)
			}

			if p := cmd.Get("paths"); p != nil && p.Value != nil {
				s.Paths = p.Value.([]string)
			}

			f := cmd.Handler.(func(context.Context, CommitArgs) error)
			err := errors.Join(f(ctx, s), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/commit")
			ctx = context.WithValue(ctx, cli.Args("/commit"), s)
		case "/remote":

			ctx = context.WithValue(ctx, cli.Parent{}, "/remote")
		case "/remote/add":
			s := RemoteAddArgs{}

			if p := cmd.Get("fetch"); p != nil && p.Value != nil {
				s.Fetch = p.Value.(bool)
			}

			if p := cmd.Get("name"); p != nil && p.Value != nil {
				s.Name = p.Value.(string)
			}

			if p := cmd.Get("url"); p != nil && p.Value != nil {
				s.URL = p.Value.(url.URL)
			}

			f := cmd.Handler.(func(context.Context, RemoteAddArgs) error)
			err := errors.Join(f(ctx, s), cmd.Cleanup())
			if err != nil {
				return cmds, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/remote/add")
			ctx = context.WithValue(ctx, cli.Args("/remote/add"), s)
		}
	}

	return cmds, nil
}
