// Code generated by cligen DO NOT EDIT

package main

import (
	"context"
	"errors"
	"net/url"
	"time"

	"github.com/lachaloupe/cli"
)

func init() {
	CLI.Register(invokeCLI)
}

func invokeCLI(ctx context.Context, args []string) ([]*cli.Command, error) {
	root := cli.Command{
		Path: "/",
		Help: "Transfer data from or to a server",
		Invoke: func(ctx context.Context, cmd *cli.Command) (context.Context, error) {
			s := Args{}

			if p := cmd.Get("method"); p != nil && p.Value != nil {
				s.Method = p.Value.(string)
			}

			if p := cmd.Get("header"); p != nil && p.Value != nil {
				s.Header = p.Value.([]string)
			}

			if p := cmd.Get("data"); p != nil && p.Value != nil {
				s.Data = p.Value.(string)
			}

			if p := cmd.Get("location"); p != nil && p.Value != nil {
				s.Location = p.Value.(bool)
			}

			if p := cmd.Get("connect-timeout"); p != nil && p.Value != nil {
				s.ConnectTimeout = p.Value.(time.Duration)
			}

			if p := cmd.Get("retry"); p != nil && p.Value != nil {
				s.Retry = p.Value.(uint)
			}

			if p := cmd.Get("output"); p != nil && p.Value != nil {
				s.Output = p.Value.(string)
			}

			if p := cmd.Get("cacert"); p != nil && p.Value != nil {
				s.Cacert = p.Value.(string)
			}

			if p := cmd.Get("proxy"); p != nil && p.Value != nil {
				s.Proxy = p.Value.(url.URL)
			}

			if p := cmd.Get("user-agent"); p != nil && p.Value != nil {
				s.UserAgent = p.Value.(string)
			}

			if p := cmd.Get("url"); p != nil && p.Value != nil {
				s.URL = p.Value.(url.URL)
			}

			err := errors.Join((RunCurl)(ctx, s), cmd.Cleanup())
			if err != nil {
				return ctx, err
			}

			ctx = context.WithValue(ctx, cli.Parent{}, "/")
			ctx = context.WithValue(ctx, cli.Args("/"), s)
			return ctx, nil
		},
		Args: []*cli.Arg{
			{
				Name:    "method",
				Type:    "string",
				Aliases: []string{"X"},
				Help:    "Request method to use.",
				Defaults: []string{
					"GET",
				},
			},
			{
				Name:    "header",
				Type:    "[]string",
				Aliases: []string{"H"},
				Help:    "Pass custom header fields to the server.",
			},
			{
				Name:    "data",
				Type:    "string",
				Aliases: []string{"d"},
				Help:    "Send data in the request body.",
			},
			{
				Name:    "location",
				Type:    "bool",
				Aliases: []string{"L"},
				Help:    "Follow redirects.",
			},
			{
				Name: "connect-timeout",
				Type: "time.Duration",
				Help: "Maximum time allowed for connection setup.",
				Defaults: []string{
					"5s",
				},
			},
			{
				Name: "retry",
				Type: "uint",
				Help: "Retry this many times on transient failures.",
			},
			{
				Name:    "output",
				Type:    "string",
				Aliases: []string{"o"},
				Help:    "Write output to this file.",
				Labels: map[string][]string{
					"path": {
						"clean",
					},
				},
				Validate: cli.PathValidate,
			},
			{
				Name: "cacert",
				Type: "string",
				Help: "Trust certificates signed only by this CA bundle.",
				Labels: map[string][]string{
					"path": {
						"exists",
						"file",
						"clean",
					},
				},
				Validate: cli.PathValidate,
			},
			{
				Name: "proxy",
				Type: "url.URL",
				Help: "Use the given proxy for the request.",
			},
			{
				Name:    "user-agent",
				Type:    "string",
				Aliases: []string{"A"},
				Help:    "Send this user agent to the server.",
				Defaults: []string{
					"curl/8.0",
				},
			},
			{
				Name:       "url",
				Type:       "url.URL",
				Help:       "URL to fetch.",
				Required:   true,
				Positional: 1,
			},
		},
	}

	cmds, err := root.Parse(ctx, args)
	if err != nil {
		return cmds, err
	}

	for _, cmd := range cmds {
		if cmd.Invoke == nil {
			continue
		}
		ctx, err = cmd.Invoke(ctx, cmd)
		if err != nil {
			return cmds, err
		}
	}

	return cmds, nil
}
